const data = [
  {
    name: "Test Whatsapp",
    region: "US",
    createdOn: 1559807714999,
    price: {
      month: "100.00",
      halfYear: "500.00",
      year: "900.00",
    },
    csv: "Some CSV link for Whatsapp",
    report: "Some report link for Whatsapp",
    image_url: "1.png",
  },
  {
    name: "Super Jewels Quest",
    region: "CA, FR",
    createdOn: 1559806715124,
    price: {
      month: "100.00",
      halfYear: "500.00",
      year: "900.00",
    },
    csv: "Some CSV link for Super Jewels Quest",
    report: "Some report link for Super Jewels Ques",
    image_url: "2.png",
  },
  {
    name: "Mole Slayer",
    region: "FR",
    createdOn: 1559806711124,
    price: {
      month: "100.00",
      halfYear: "500.00",
      year: "900.00",
    },
    csv: "Some CSV link for Mole Slayer",
    report: "Some report link for Mole Slayer",
    image_url: "3.png",
  },
  {
    name: "Mancala Mix",
    region: "JP",
    createdOn: 1559806680124,
    price: {
      month: "100.00",
      halfYear: "500.00",
      year: "900.00",
    },
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "4.png",
  },
  {
    name: "Mancala Mix",
    region: "JP",
    createdOn: 9959806680124,
    price: {
      month: "100.00",
      halfYear: "500.00",
      year: "900.00",
    },
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "5.png",
  },
  {
    name: "Mancala Mix",
    region: "JP",
    createdOn: 1627799944115,
    price: {
      month: "100.00",
      halfYear: "500.00",
      year: "900.00",
    },
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "6.png",
  },
  {
    name: "Mancala Mix",
    region: "JP",
    createdOn: 1627792890187,
    price: {
      month: "100.00",
      halfYear: "500.00",
      year: "900.00",
    },
    csv: "Some CSV link for Mancala Mix",
    report: "Some report link for Mancala Mix",
    image_url: "7.png",
  },
];
export default data;
